### ISSUE TITLE
Specs are failing under JRuby 9000

### ISSUE THREAD

**Issue by newellista** [liveh2o/spectacles#16]
```
# Running:

...............EEEE............DEPRECATION WARNING: NewProductUser is an abstract class and should not be instantiated. In v1.0, calling `NewProductUser.new` will raise a NotImplementedError.
....

Fabulous run in 0.430607s, 81.2806 runs/s, 127.7267 assertions/s.

  1) Error:
Spectacles::SchemaStatements::PostgreSQLAdapter::ActiveRecord::SchemaDumper#dump#test_0004_should rebuild views in dump stream:
NoMethodError: private method `gsub' called for ["fillfactor=50"]:Array
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_statements/postgresql_adapter.rb:137:in `parse_storage_definition'
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_statements/postgresql_adapter.rb:70:in `materialized_view_build_query'
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_dumper.rb:32:in `dump_materialized_view'
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_dumper.rb:15:in `block in dump_materialized_views'
    org/jruby/RubyArray.java:1560:in `each'
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_dumper.rb:14:in `dump_materialized_views'
    /Users/stevenewell/projects/spectacles/lib/spectacles.rb:40:in `trailer'
    /Users/stevenewell/.rvm/gems/jruby-head/gems/activerecord-4.2.1/lib/active_record/schema_dumper.rb:39:in `dump'
    /Users/stevenewell/.rvm/gems/jruby-head/gems/activerecord-4.2.1/lib/active_record/schema_dumper.rb:22:in `dump'
    /Users/stevenewell/projects/spectacles/specs/support/schema_statement_examples.rb:56:in `block in test_0004_should rebuild views in dump stream'


  2) Error:
Spectacles::SchemaStatements::PostgreSQLAdapter::ActiveRecord::SchemaDumper#dump#test_0001_should return create_view in dump stream:
NoMethodError: private method `gsub' called for ["fillfactor=50"]:Array
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_statements/postgresql_adapter.rb:137:in `parse_storage_definition'
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_statements/postgresql_adapter.rb:70:in `materialized_view_build_query'
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_dumper.rb:32:in `dump_materialized_view'
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_dumper.rb:15:in `block in dump_materialized_views'
    org/jruby/RubyArray.java:1560:in `each'
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_dumper.rb:14:in `dump_materialized_views'
    /Users/stevenewell/projects/spectacles/lib/spectacles.rb:40:in `trailer'
    /Users/stevenewell/.rvm/gems/jruby-head/gems/activerecord-4.2.1/lib/active_record/schema_dumper.rb:39:in `dump'
    /Users/stevenewell/.rvm/gems/jruby-head/gems/activerecord-4.2.1/lib/active_record/schema_dumper.rb:22:in `dump'
    /Users/stevenewell/projects/spectacles/specs/support/schema_statement_examples.rb:35:in `block in test_0001_should return create_view in dump stream'


  3) Error:
Spectacles::SchemaStatements::PostgreSQLAdapter::ActiveRecord::SchemaDumper#dump#test_0002_should return create_materialized_view in dump stream:
NoMethodError: private method `gsub' called for ["fillfactor=50"]:Array
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_statements/postgresql_adapter.rb:137:in `parse_storage_definition'
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_statements/postgresql_adapter.rb:70:in `materialized_view_build_query'
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_dumper.rb:32:in `dump_materialized_view'
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_dumper.rb:15:in `block in dump_materialized_views'
    org/jruby/RubyArray.java:1560:in `each'
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_dumper.rb:14:in `dump_materialized_views'
    /Users/stevenewell/projects/spectacles/lib/spectacles.rb:40:in `trailer'
    /Users/stevenewell/.rvm/gems/jruby-head/gems/activerecord-4.2.1/lib/active_record/schema_dumper.rb:39:in `dump'
    /Users/stevenewell/.rvm/gems/jruby-head/gems/activerecord-4.2.1/lib/active_record/schema_dumper.rb:22:in `dump'
    /Users/stevenewell/projects/spectacles/specs/support/schema_statement_examples.rb:42:in `block in test_0002_should return create_materialized_view in dump stream'


  4) Error:
Spectacles::SchemaStatements::PostgreSQLAdapter::ActiveRecord::SchemaDumper#dump#test_0003_should include options for create_materialized_view:
NoMethodError: private method `gsub' called for ["fillfactor=50"]:Array
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_statements/postgresql_adapter.rb:137:in `parse_storage_definition'
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_statements/postgresql_adapter.rb:70:in `materialized_view_build_query'
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_dumper.rb:32:in `dump_materialized_view'
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_dumper.rb:15:in `block in dump_materialized_views'
    org/jruby/RubyArray.java:1560:in `each'
    /Users/stevenewell/projects/spectacles/lib/spectacles/schema_dumper.rb:14:in `dump_materialized_views'
    /Users/stevenewell/projects/spectacles/lib/spectacles.rb:40:in `trailer'
    /Users/stevenewell/.rvm/gems/jruby-head/gems/activerecord-4.2.1/lib/active_record/schema_dumper.rb:39:in `dump'
    /Users/stevenewell/.rvm/gems/jruby-head/gems/activerecord-4.2.1/lib/active_record/schema_dumper.rb:22:in `dump'
    /Users/stevenewell/projects/spectacles/specs/support/schema_statement_examples.rb:48:in `block in test_0003_should include options for create_materialized_view'

35 runs, 55 assertions, 0 failures, 4 errors, 0 skips
```

**Comment by newellista** [comment]
They also fail under `jruby-1.7.19`

```
$ bundle exec rake test:postgresql
file:/Users/stevenewell/.rvm/rubies/jruby-1.7.19/lib/jruby.jar!/jruby/kernel19/kernel.rb:28 warning: unsupported exec option: close_others
/Users/stevenewell/.rvm/rubies/jruby-1.7.19/bin/jruby -I"lib:lib:specs" -I"/Users/stevenewell/.rvm/gems/jruby-1.7.19/gems/rake-10.4.2/lib" "/Users/stevenewell/.rvm/gems/jruby-1.7.19/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "specs/adapters/postgresql*_spec.rb"
Coverage may be inaccurate; Try setting JRUBY_OPTS="-Xcli.debug=true --debug"
/Users/stevenewell/.rvm/gems/jruby-1.7.19/gems/simplecov-0.10.0/lib/simplecov.rb:43 warning: tracing (e.g. set_trace_func) will not capture all events without --debug flag
NOTE: ActiveRecord 4.2 is not (yet) fully supported by AR-JDBC, please help us finish 4.2 support - check http://bit.ly/jruby-42 for starters
NoMethodError: undefined method `prepend' for ActiveRecord::ConnectionAdapters::MysqlAdapter:Class
       load_adapters at /Users/stevenewell/projects/spectacles/lib/spectacles/schema_statements.rb:16
                each at org/jruby/RubyArray.java:1613
       load_adapters at /Users/stevenewell/projects/spectacles/lib/spectacles/schema_statements.rb:7
           inherited at /Users/stevenewell/projects/spectacles/lib/spectacles.rb:30
  ConnectionAdapters at /Users/stevenewell/.rvm/gems/jruby-1.7.19/gems/activerecord-jdbc-adapter-1.3.17/lib/arjdbc/mysql/adapter.rb:952
        ActiveRecord at /Users/stevenewell/.rvm/gems/jruby-1.7.19/gems/activerecord-jdbc-adapter-1.3.17/lib/arjdbc/mysql/adapter.rb:948
              (root) at /Users/stevenewell/.rvm/gems/jruby-1.7.19/gems/activerecord-jdbc-adapter-1.3.17/lib/arjdbc/mysql/adapter.rb:947
             require at org/jruby/RubyKernel.java:1071
             require at /Users/stevenewell/.rvm/gems/jruby-1.7.19@global/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274
     load_dependency at /Users/stevenewell/.rvm/gems/jruby-1.7.19@global/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240
             require at /Users/stevenewell/.rvm/gems/jruby-1.7.19@global/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274
              (root) at /Users/stevenewell/.rvm/gems/jruby-1.7.19/gems/activerecord-jdbc-adapter-1.3.17/lib/arjdbc/mysql.rb:1
             require at org/jruby/RubyKernel.java:1071
             require at /Users/stevenewell/.rvm/gems/jruby-1.7.19@global/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274
     load_dependency at /Users/stevenewell/.rvm/gems/jruby-1.7.19@global/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240
             require at /Users/stevenewell/.rvm/gems/jruby-1.7.19@global/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274
              (root) at /Users/stevenewell/.rvm/gems/jruby-1.7.19/gems/activerecord-jdbc-adapter-1.3.17/lib/arjdbc/mysql.rb:2
             require at org/jruby/RubyKernel.java:1071
              (root) at /Users/stevenewell/.rvm/gems/jruby-1.7.19/gems/activerecord-jdbcmysql-adapter-1.3.16/lib/activerecord-jdbcmysql-adapter.rb:1
                each at org/jruby/RubyArray.java:1613
              (root) at /Users/stevenewell/.rvm/gems/jruby-1.7.19/gems/activerecord-jdbcmysql-adapter-1.3.16/lib/activerecord-jdbcmysql-adapter.rb:3
                each at org/jruby/RubyArray.java:1613
              (root) at /Users/stevenewell/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:1
             require at /Users/stevenewell/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:76
             require at /Users/stevenewell/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:72
             require at org/jruby/RubyKernel.java:1071
             require at /Users/stevenewell/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:61
             require at org/jruby/RubyKernel.java:1071
              (root) at /Users/stevenewell/.rvm/gems/jruby-1.7.19/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:10
                each at org/jruby/RubyArray.java:1613
              (root) at /Users/stevenewell/.rvm/gems/jruby-1.7.19/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:9
              select at org/jruby/RubyArray.java:2468
              (root) at /Users/stevenewell/.rvm/gems/jruby-1.7.19/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4
Coverage report generated for RSpec to /Users/stevenewell/projects/spectacles/coverage. 98 / 177 LOC (55.37%) covered.
rake aborted!
SignalException: 1
/Users/stevenewell/.rvm/gems/jruby-1.7.19/bin/jruby_executable_hooks:15:in `(root)'
Tasks: TOP => test:postgresql
(See full trace by running task with --trace)
```
